### ISSUE TITLE
После удаления и повторной установки приложения 

### ISSUE THREAD

**Issue by karapetyan** [hello-kozloff/finbox-mini-app#1]
Значение счетчика займов в верхнем блоке не соответствует действительности. Предполагаю, что это связано как-то с переустановкой приложения и очисткой кэша.

Записей о полученных займах нет, а сумма полученных займов есть. 
Аналогичная проблема возможна и в выданных займах.
![image](https://user-images.githubusercontent.com/1526786/105720732-d156d900-5f34-11eb-96fb-a6ff16aef6e1.png)

**Comment by hello-kozloff** [comment]
Closed
